config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resource :dashboard, only: [:show]
  get '/auth/:provider', to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'

  get '/repos/:owner/:id', to: 'repos#show', as: :repo

  resources :users, only: [:edit, :update]
  resources :repos, except: :show do
    resources :deployments
  end

  post "/deployments/callback"
end

app/models/commit.rb
class Commit < SimpleDelegator
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def story_ids
    commit.message.lines.grep(/Finishes/).map {|line| line.match(/#(\d+)/)[1].to_i }
  end
end

app/models/deployment.rb
class Deployment < ActiveRecord::Base
  belongs_to :user, foreign_key: :owner_id
  def repo
    @repo ||= github.repo(repo_id.to_i)
  end

  def stories
    story_ids = commits_by_story_id.keys
    stories = tracker.project(tracker_project_id).stories(filter: story_ids.join(','))
    stories_by_id = stories.each_with_object({}) {|story, h| h[story.id] = Story.new(story)}
    commits_by_story_id.map do |story_id, commits|
      stories_by_id[story_id].commits = commits.map(&:sha)
    end
    stories_by_id.values
  end

  def commits_by_story_id
    commits.each_with_object({}) do |commit, h|
      commit.story_ids.each do |story_id|
        h[story_id] ||= []
        h[story_id] << commit
      end
    end
  end

  def commits
    @commits ||= github.compare(repo_id, starting_commit, upto).commits.map do |c|
      Commit.new(c)
    end
  end

  def starting_commit
    from.presence || github.commits(repo_id, per_page: 50).last.sha
  end

  private

  def github
    @github ||= Github.new(user.token)
  end

  def tracker
    @tracker ||= TrackerApi::Client.new(token: user.tracker_token)
  end
end

app/models/github.rb
class Github < SimpleDelegator
  def initialize(token)
    super(Octokit::Client.new(access_token: token))
  end
end

app/models/repo.rb
class Repo < SimpleDelegator
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def deployments
    @deployments ||= Deployment.where(repo_id: to_param)
  end

  def to_param
    [self.id.to_i]
  end

  def persisted?
    false
  end
end

app/models/story.rb
class Story < SimpleDelegator
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  attr_accessor :commits

  def initialize(story)
    super
    @commits = []
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth_hash(h)
    User.find_or_create_by!(provider: h[:provider], github_uid: h[:uid]).tap do |u|
      u.update!(
        username: h[:info][:nickname],
        token: h[:credentials][:token],
        secret: h[:credentials][:secret],
        token_expires_at: h[:credentials][:expires_at]
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @user ||= (User.find_by(id: session[:user_id]) || NullUser.new)
  end
  helper_method :current_user

  class NullUser
    def username
      'Guest'
    end

    def token
      ''
    end
    
    def persisted?
      false
    end
  end
  private_constant :NullUser

  def authenticated?
    current_user.persisted?
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < GithubController
  def show
    @repos = github.repos
  end
end

app/controllers/deployments_controller.rb
class DeploymentsController < GithubController
  before_action :set_repo, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_deployment, only: [:show, :edit, :update, :destroy]
  before_filter :owns_deployment?, only: [:index, :show, :new, :edit, :update, :destroy]
  protect_from_forgery except: :callback

  # GET /deployments
  # GET /deployments.json
  def index
    @deployments = Deployment.all
  end

  # GET /deployments/1
  # GET /deployments/1.json
  def show
  end

  # GET /deployments/new
  def new
    @deployment = Deployment.new
  end

  # GET /deployments/1/edit
  def edit
  end

  # POST /deployments
  # POST /deployments.json
  def create
    @deployment = Deployment.new(deployment_params)

    respond_to do |format|
      if @deployment.save
        format.html { redirect_to repo_deployment_path(@repo.id, @deployment), notice: 'Deployment was successfully created.' }
        format.json { render :show, status: :created, location: @deployment }
      else
        format.html { render :new }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deployments/1
  # PATCH/PUT /deployments/1.json
  def update
    respond_to do |format|
      if @deployment.update(deployment_params)
        format.html { redirect_to repo_deployment_path(@repo.id, @deployment), notice: 'Deployment was successfully updated.' }
        format.json { render :show, status: :ok, location: @deployment }
      else
        format.html { render :edit }
        format.json { render json: @deployment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deployments/1
  # DELETE /deployments/1.json
  def destroy
    @deployment.destroy
    respond_to do |format|
      format.html { redirect_to repo_path(owner: @repo.owner.login, id: @repo.name), notice: 'Deployment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def callback
    environment = params[:deployment][:environment]
    repo_id = params[:repository][:id]
    new_sha = params[:deployment][:sha]
    Deployment.where(name: environment, repo_id: repo_id).update_all('`from` = `upto`')
    Deployment.where(name: environment, repo_id: repo_id).update_all(upto: new_sha)
    render json: {}, status: :ok
  end

  private
  def set_repo
    @repo = Repo.new(github.repo(params[:repo_id].to_i))
  end

  def set_deployment
    @deployment = Deployment.find_by('id = ? OR name = ?', params[:id], params[:id])
  end

  def deployment_params
    params.require(:deployment)
      .permit(:from, :upto, :name, :tracker_project_id)
      .merge(repo_id: @repo.id, owner_id: current_user.id)
  end

  def owns_deployment?
    redirect_to root_path unless @repo
  end
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  before_filter :authenticated?

  private
  def github
    @github ||= Octokit::Client.new(access_token: current_user.token)
  end
  helper_method :github
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.persisted?
      redirect_to dashboard_path
      return
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < GithubController
  def show
    @repo = Repo.new(github.repo(repo))
  end

  private
  def repo
    "#{params[:owner]}/#{params[:id]}"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < GithubController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to root_path, notice: "Success!"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:tracker_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deployments_helper.rb
module DeploymentsHelper
end

app/views/dashboards/show.html.erb
<%= link_to 'Edit Profile', edit_user_path(current_user) %>
<ul>
  <%- @repos.each do |repo| %>
    <li>
      <%= link_to repo.name, repo_path(owner: repo.owner.login, id: repo.name) %>
    </li>
  <% end %>
</ul>

app/views/deployments/_form.html.erb
<%= form_for([@repo, @deployment], url: @deployment.new_record? ? repo_deployments_path(@repo.id) : repo_deployment_path(@repo.id, @deployment)) do |f| %>
  <% if @deployment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deployment.errors.count, "error") %> prohibited this deployment from being saved:</h2>

      <ul>
      <% @deployment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tracker_project_id %><br>
    <%= f.text_field :tracker_project_id %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :upto %><br>
    <%= f.text_field :upto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deployments/edit.html.erb
<h1>Editing Deployment</h1>

<%= render 'form' %>

<%= link_to 'Show', repo_deployment_path(@repo.id, @deployment) %> |
<%= link_to 'Back', repo_path(owner: @repo.owner.login, id: @repo.name) %>

app/views/deployments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deployments</h1>

<table>
  <thead>
    <tr>
      <th>Repo</th>
      <th>From</th>
      <th>Upto</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deployments.each do |deployment| %>
      <tr>
        <td><%= deployment.repo %></td>
        <td><%= deployment.from %></td>
        <td><%= deployment.upto %></td>
        <td><%= deployment.name %></td>
        <td><%= link_to 'Show', deployment %></td>
        <td><%= link_to 'Edit', edit_deployment_path(deployment) %></td>
        <td><%= link_to 'Destroy', deployment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deployment', new_deployment_path %>

app/views/deployments/new.html.erb
<h1>New Deployment</h1>

<%= render 'form' %>

<%= link_to 'Back', repo_path(owner: @repo.owner.login, id: @repo.name) %>

app/views/deployments/show.html.erb
<h1><%= @deployment.repo.name %> deployment to <%= @deployment.name %></h1>
<p>
  <strong>From:</strong>
  <%= @deployment.starting_commit %>
  <%- if @deployment.from.blank? %>
    (This commit is 50 commits behind because no FROM commit was specified)
  <% end %>
</p>

<p>
  <strong>Upto:</strong>
  <%= @deployment.upto %>
</p>

<hr/>
<h3>Stories</h3>
<ul class='list-unstyled'>
  <% @deployment.stories.each do |story| %>
    <li>
      <h3 data-collapse='true'>
        <i class='glyphicon collapse-closed'></i>
        <%= story.id %>: <%= story.name %>
      </h3>
      <div data-collapsed='true'>
        <p>Commits: <%= story.commits.join(', ') %></p>
        <pre><%= story.description %></pre>
      </div>
    </li>
  <% end %>
</ul>

<hr/>

<%= link_to 'Edit', edit_repo_deployment_path(@repo.id, @deployment) %> |
<%= link_to 'Back', repo_path(owner: @repo.owner.login, id: @repo.name) %>

app/views/home/index.html.erb
<div class='col-md-4 col-md-offset-4'>
  <p class='text-center'>Welcome!</p>
  <%= link_to 'Login with GitHub', login_path(provider: :github), class: 'btn btn-primary' %>
  <%= link_to 'Login with BitBucket', login_path(provider: :bitbucket), class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commitment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
  <div class='row'>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/repos/show.html.erb
<h1><%= @repo.name %></h1>
<ul>
  <%- @repo.deployments.each do |deployment| %>
    <li>
      <%= link_to deployment.name, repo_deployment_path(@repo.id, deployment) %>
      |
      <%= link_to 'Destroy', repo_deployment_path(@repo.id, deployment), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add deployment', new_repo_deployment_path(repo_id: @repo.id) %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.label :tracker_token %>
  <%= f.text_field :tracker_token %>

  <%= f.submit %>
<% end %>